"""Writes Mesh objects as Forge OBJ block models (obj + mtl + block/item model json)."""
import json
import math
import os

from mesh import _cross, _sub

MOD = "stagetents"


def write_model(mesh, name, assets, textures, tinted=(), particle=None, gui_scale=0.625, gui_offset=(0, 0, 0),
                render_type="minecraft:cutout"):
    """Exports {mesh} as models/block/props/{name}.obj and its json models.

    textures: material -> texture location (e.g. "stagetents:block/props/metal").
    tinted: materials that take the block colour (tint index 0).
    """
    folder = os.path.join(assets, "models", "block", "props")
    os.makedirs(folder, exist_ok=True)
    _write_obj(mesh, os.path.join(folder, name + ".obj"), name)
    with open(os.path.join(folder, name + ".mtl"), "w", encoding="utf-8", newline="\n") as f:
        for mat in mesh.groups:
            f.write(f"newmtl {mat}\nKd 1 1 1\nmap_Kd #{mat}\n")
            # Forge tints every OBJ material with index 0 unless told otherwise.
            f.write("forge_TintIndex 0\n" if mat in tinted else "forge_TintIndex -1\n")
            f.write("\n")
    model = {
        "loader": "forge:obj",
        "model": f"{MOD}:models/block/props/{name}.obj",
        "flip_v": True,
        "shade_quads": True,
        "automatic_culling": False,
        "emissive_ambient": True,
        "render_type": render_type,
        "textures": {"particle": particle or textures[next(iter(mesh.groups))]},
    }
    for mat in mesh.groups:
        model["textures"][mat] = textures[mat]
    _json(os.path.join(assets, "models", "block", "props", name + ".json"), model)
    s = gui_scale
    item = {
        "parent": f"{MOD}:block/props/{name}",
        "display": {
            "gui": {"rotation": [30, 225, 0], "translation": list(gui_offset), "scale": [s, s, s]},
            "ground": {"rotation": [0, 0, 0], "translation": [0, 3, 0], "scale": [s * 0.4, s * 0.4, s * 0.4]},
            "fixed": {"rotation": [0, 0, 0], "translation": [0, 0, 0], "scale": [s * 0.8, s * 0.8, s * 0.8]},
            "thirdperson_righthand": {"rotation": [75, 45, 0], "translation": [0, 2.5, 0], "scale": [s * 0.6, s * 0.6, s * 0.6]},
            "firstperson_righthand": {"rotation": [0, 45, 0], "translation": [0, 0, 0], "scale": [s * 0.64, s * 0.64, s * 0.64]},
            "firstperson_lefthand": {"rotation": [0, 225, 0], "translation": [0, 0, 0], "scale": [s * 0.64, s * 0.64, s * 0.64]},
        },
    }
    _json(os.path.join(assets, "models", "item", name + ".json"), item)


def _write_obj(mesh, path, name):
    lines = [f"# {name}: generated by tools/props", f"mtllib {name}.mtl", f"o {name}"]
    vi = vt = vn = 0
    body = []
    for mat, tris in mesh.groups.items():
        body.append(f"usemtl {mat}")
        for t in tris:
            # Winding follows the vertex normals (front faces counter-clockwise).
            (a, na, ua), (b, nb, ub), (c, nc, uc) = t
            g = _cross(_sub(b, a), _sub(c, a))
            avg = (na[0] + nb[0] + nc[0], na[1] + nb[1] + nc[1], na[2] + nb[2] + nc[2])
            if g[0] * avg[0] + g[1] * avg[1] + g[2] * avg[2] < 0:
                t = (t[0], t[2], t[1])
            t = _fit_uvs(t)
            idx = []
            for (p, n, uv) in t:
                lines.append(f"v {p[0]:.5f} {p[1]:.5f} {p[2]:.5f}")
                lines.append(f"vt {uv[0]:.5f} {uv[1]:.5f}")
                lines.append(f"vn {n[0]:.4f} {n[1]:.4f} {n[2]:.4f}")
                vi += 1; vt += 1; vn += 1
                idx.append(f"{vi}/{vt}/{vn}")
            body.append("f " + " ".join(idx))
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines + body) + "\n")


def _fit_uvs(t):
    """Block textures live side by side in an atlas and don't repeat: uvs outside 0..1 would sample the neighbouring
    sprites. Shift each triangle's uvs into the unit square, and shrink the ones that span more than one tile."""
    us = [v[2][0] for v in t]
    vs = [v[2][1] for v in t]
    out = []
    du, dv = math.floor(min(us)), math.floor(min(vs))
    su = max(1.0, max(us) - min(us))
    sv = max(1.0, max(vs) - min(vs))
    # Keep the triangle where it falls in its tile when it fits, otherwise slide it back inside.
    ou = min(min(us) - du, 1.0 - (max(us) - min(us)) / su)
    ov = min(min(vs) - dv, 1.0 - (max(vs) - min(vs)) / sv)
    for (p, n, uv) in t:
        u = (uv[0] - min(us)) / su + ou
        v = (uv[1] - min(vs)) / sv + ov
        out.append((p, n, (min(1.0, max(0.0, u)), min(1.0, max(0.0, v)))))
    return tuple(out)


def _json(path, obj):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(obj, f, indent=2)
        f.write("\n")
