"""Pixel-art inventory icons (16x16) for the stage and site props, in the flat front-view style of the tent items.

Layer 0 holds the fixed colours; layer 1 holds the dyed part in greys, tinted in game with the block's colour.
"""
import json
import os

from PIL import Image

N = 16
FIXED = {
    "K": (38, 38, 42), "k": (68, 68, 74), "g": (104, 108, 114), "s": (154, 158, 166), "S": (198, 200, 206),
    "C": (234, 236, 240), "W": (242, 240, 234), "w": (206, 204, 198), "B": (120, 86, 58), "b": (90, 64, 44),
    "R": (194, 46, 38), "G": (80, 200, 110), "L": (58, 100, 210), "Y": (242, 198, 46),
}
TINT = {"1": 246, "2": 212, "3": 172, "4": 128}

ICONS = {
    # Praticable: plateau phénolique, cadre alu, jupe velours plissée, pieds.
    "stage_deck": [
        "................",
        ".CSSSSSSSSSSSSC.",
        ".SBBBBBBBBBBBBS.",
        ".SbbbbbbbbbbbbS.",
        ".SSSSSSSSSSSSSS.",
        ".k112211221122k.",
        ".k221122112211k.",
        ".k112211221122k.",
        ".k221122112211k.",
        ".k332233223322k.",
        ".k334433443344k.",
        ".k443344334433k.",
        ".KKKKKKKKKKKKKK.",
        "KK............KK",
        ".kk..........kk.",
        "................",
    ],
    # Cyclo de profil: barre, toile, gorge au sol, sac de sable.
    "cyclorama": [
        "........CCSSS...",
        "........kSSSk...",
        "........12221...",
        "........12221...",
        "........12221...",
        "........23332...",
        "........23332...",
        "........34443...",
        ".......344443...",
        "......3444443...",
        ".....34444443...",
        "....344444443...",
        "...ww444444ww...",
        "..KKKwwwwKKK....",
        "...KKKKKKKK.....",
        "................",
    ],
    # Flight case: coins à boule, bandeau, grenouillères, étiquette, roulettes.
    "flight_case": [
        "................",
        "..CSSSSSSSSSSC..",
        "..SCkkkkkkkkCS..",
        "..Sk11111111kS..",
        "..SkKKKKKKKKkS..",
        "..SkC.C.C.C.kS..",
        "..SkK.K.K.K.kS..",
        "..Sk.WWWWWW.kS..",
        "..Sk.wwwwww.kS..",
        "..SkKKKKKKKKkS..",
        "..SCkkkkkkkkCS..",
        "..CSSSSSSSSSSC..",
        "...Kk......kK...",
        "...kk......kk...",
        "................",
        "................",
    ],
    # Malle large et basse, une rangée de grenouillères.
    "flight_case_trunk": [
        "................",
        "................",
        "................",
        "CSSSSSSSSSSSSSSC",
        "SCkkkkkkkkkkkkCS",
        "Sk111111111111kS",
        "Sk.CC..CC..CC.kS",
        "Sk.kk..kk..kk.kS",
        "SkKWWWWWWWWWWKkS",
        "SkKwwwwwwwwwwKkS",
        "SkkkkkkkkkkkkkkS",
        "CSSSSSSSSSSSSSSC",
        ".KK..........KK.",
        ".kk..........kk.",
        "................",
        "................",
    ],
    # Tour étroite, deux rangées de grenouillères.
    "flight_case_tall": [
        "...CSSSSSSSC....",
        "...SCkkkkkCS....",
        "...Sk11111kS....",
        "...Sk..CC.kS....",
        "...Sk..kk.kS....",
        "...SkKKKKKkS....",
        "...SkWWWWWkS....",
        "...SkwwwwwkS....",
        "...SkKKKKKkS....",
        "...Sk..CC.kS....",
        "...Sk..kk.kS....",
        "...SkKKKKKkS....",
        "...SCkkkkkCS....",
        "...CSSSSSSSC....",
        "....KK..KK......",
        "....kk..kk......",
    ],
    # Grande caisse, deux rangées de grenouillères.
    "flight_case_xl": [
        "CSSSSSSSSSSSSSSC",
        "SCkkkkkkkkkkkkCS",
        "Sk111111111111kS",
        "Sk.CC..CC..CC.kS",
        "Sk.kk..kk..kk.kS",
        "SkKKKKKKKKKKKKkS",
        "SkK.WWWWWWWW.KkS",
        "SkK.wwwwwwww.KkS",
        "SkKKKKKKKKKKKKkS",
        "Sk.CC..CC..CC.kS",
        "Sk.kk..kk..kk.kS",
        "SkkkkkkkkkkkkkkS",
        "CSSSSSSSSSSSSSSC",
        ".KK..........KK.",
        ".kk..........kk.",
        "................",
    ],
    # Groupe silencieux: capot, ouïes, prises, arrêt d'urgence, pot, fourches.
    "generator": [
        "................",
        "......SSSs......",
        ".....SkkkS..C...",
        ".11111111111111.",
        ".12222222222223.",
        ".1kkkk122222223.",
        ".122221222LLLL3.",
        ".1kkkk122LRLRL3.",
        ".12222122KKKKR3.",
        ".1kkkk1222222Y3.",
        ".13333333333333.",
        ".KKKKKKKKKKKKKK.",
        ".KkkK....KkkK.K.",
        ".KKKKKKKKKKKKKK.",
        "................",
        "................",
    ],
    # Mât d'éclairage: quatre projecteurs, mât, capot, prises, arrêt d'urgence, châssis.
    "light_tower": [
        "................",
        ".....WW..WW.....",
        ".....WW..WW.....",
        "......SSSS......",
        ".......SS.......",
        ".......SS.......",
        ".......SS.......",
        ".......SS.......",
        ".22222222222222.",
        ".2kkkk222LLLLL2.",
        ".2kkkk22LRLRLY2.",
        ".23333333333332.",
        ".KKKKKKKKKKKKKK.",
        "..KK......KK.K..",
        "................",
        "................",
    ],
    # Tour régie: échafaudage, planchers, toit et bâches teintés.
    "control_tower": [
        "................",
        "..222222222222..",
        "..2SSSSSSSSSS2..",
        "..2S.SS..SS.S2..",
        "..2S........S2..",
        "..2SSSSSSSSSS2..",
        "..2S.SS..SS.S2..",
        "..2S........S2..",
        "..2SSSSSSSSSS2..",
        "..2S.SS..SS.S2..",
        "..2S........S2..",
        "..SSSSSSSSSSSS..",
        "..S..........S..",
        "..S..........S..",
        ".KK..........KK.",
        "................",
    ],
    # Point d'eau: rail, dosseret, robinet, savon, bassine, caisson, pédale, poubelle.
    "wash_station": [
        "................",
        "......CCCC......",
        ".....C....C.....",
        "....SSSSSSSS....",
        "....S.CC.WW.S...",
        "....SSSSSSSS....",
        "...ssssssssss...",
        "...skkkkkkkks...",
        "...skkkkkkkks...",
        "...ssssssssss...",
        "....ssssssss....",
        "....ssssssss....",
        "....s......s....",
        "....s..KK..s....",
        ".....sKKKKs.....",
        "......ssss......",
    ],
    # Sanitaire de chantier: dôme, porte nervurée, voyant, manche, évent.
    "site_toilet": [
        ".....WWWWW......",
        "....WWWWWWW..K..",
        "...WWWWWWWWW.Kk.",
        "..WWWWWWWWWWWKk.",
        ".W222222222222W.",
        ".W21k1111k1112W.",
        ".W21k1W11k1112W.",
        ".W21kWWW1k1112W.",
        ".W21k1111k1R12W.",
        ".W21k1111k11C2W.",
        ".W21k1111k1112W.",
        ".W21k1111k1112W.",
        ".W222222222222W.",
        "..gggggggggggg..",
        ".KKKKKKKKKKKKKK.",
        "................",
    ],
    # Grillage Heras: cadre, maille, brise-vue, pieds caoutchouc.
    "site_fence": [
        ".SSSSSSSSSSSSSS.",
        "S.s.s.s.s.s.s.sS",
        "S.s.s.s.s.s.s.sS",
        "S11111111111111S",
        "S11221122112211S",
        "S11221122112211S",
        "S22332233223322S",
        "S22332233223322S",
        "S33443344334433S",
        ".SSSSSSSSSSSSSS.",
        "KKKK........KKKK",
        "Kkkk........kkkK",
        ".KK..........KK.",
        "................",
        "................",
        "................",
    ],
    # Oriflamme: pied en croix, mât cintré, plume.
    "oriflamme": [
        "..........11....",
        ".........1221...",
        "........122221..",
        ".......1222221..",
        "......12222221..",
        ".....112222221..",
        ".....K12222221..",
        ".....K1222221...",
        ".....K.122221...",
        ".....K..12221...",
        ".....K...111....",
        ".....KK.........",
        "......K.........",
        ".....KKK........",
        "....K.K.K.......",
        "...KK.K.KK......",
    ],
    # Escalier de scène: quatre marches alu, nez teintés, main courante.
    "stage_stairs": [
        ".............C..",
        "............C1S.",
        "...........C.1S.",
        "..........C11kS.",
        ".........C122kS.",
        "........C11kkSS.",
        ".......C122ksSS.",
        "......C133kssSS.",
        ".....C11kksssSS.",
        "....C122kssssSS.",
        "...C133ksssssSS.",
        "..C11kkssssssSS.",
        ".C122ksssssssKK.",
        "CKKKksssssssssk.",
        "k.............k.",
        "................",
    ],
    # Rampe: plan incliné, nez teinté, bandes antidérapantes, lisse.
    "stage_ramp": [
        "..............C.",
        ".............C1S",
        "............C.1S",
        "...........C..sS",
        "..........C.K.sS",
        ".........C..s.kS",
        "........C.K..skS",
        ".......C..s.sskS",
        "......C.K..ssskS",
        ".....C..s.sssskS",
        "....C.K..ssssskS",
        "...C..s.sssssskS",
        "..C.K..ssssssskS",
        ".C....sssssssssk",
        "KKKKKKKKKKKKKKKK",
        "k..............k",
    ],
    # Frise: tube, tombé court, ourlet festonné.
    "frise": [
        "................",
        "................",
        "................",
        ".CSSSSSSSSSSSSC.",
        ".k111111111111k.",
        "1122112211221122",
        "1221122112211221",
        "1122112211221122",
        "221122..221122..",
        ".2211....2211...",
        "..22......22....",
        "...2......2.....",
        "................",
        "................",
        "................",
        "................",
    ],
    # Pendrillon: tube, tête froncée, jambe plissée jusqu'au sol.
    "pendrillon": [
        ".CSSSSSSSSSSSSC.",
        ".k111111111111k.",
        "1122112211221122",
        "1221122112211221",
        "1122112211221122",
        "1221122112211221",
        "2332233223322332",
        "3223322332233223",
        "2332233223322332",
        "3443344334433443",
        "4334433443344334",
        "3443344334433443",
        "4334433443344334",
        "3443344334433443",
        "4444444444444444",
        "4444444444444444",
    ],
    # Table ronde nappée jusqu'au sol, plis verticaux.
    "round_table": [
        "................",
        ".....CCCCCC.....",
        "....C111111C....",
        "...C12222221C...",
        "..112222222221..",
        "..1223322233221.",
        "..1223322233221.",
        "..1334433344331.",
        "..1334433344331.",
        "..1444433344441.",
        "..1333333333331.",
        "..1222222222221.",
        "...11111111111..",
        "....11111111....",
        "................",
        "................",
    ],
    # Mange-debout sous housse: plateau, taille pincée, nœud, pied large.
    "standing_table": [
        "................",
        "....CCCCCCCC....",
        "...C11111111C...",
        "....12222221....",
        ".....133331.....",
        "......1221......",
        "......1CC1......",
        "......1221......",
        ".....122221.....",
        "....12222221....",
        "...1222222221...",
        "..122222222221..",
        "..133333333331..",
        "...1444444441...",
        "....11111111....",
        "................",
    ],
    # Chaise Chiavari: pommes dorées, barreaux, coussin, pieds tournés.
    "banquet_chair": [
        "....Y......Y....",
        "....S......S....",
        "....S111111S....",
        "....S1.11.1S....",
        "....S111111S....",
        "....S......S....",
        "....S......S....",
        "...1122222211...",
        "..122222222221..",
        "..133333333331..",
        "...1111111111...",
        "...SS....SS.....",
        "...SS....SS.....",
        "..KK......KK....",
        ".KK........KK...",
        "................",
    ],
    # Chaise pliante: dossier et assise plastique, piètement en X.
    "folding_chair": [
        "........1111....",
        ".......122221...",
        ".......133331...",
        ".......11111....",
        "....1122222211..",
        "....1333333331..",
        "...K........K...",
        "..K........K....",
        ".K........K.....",
        "K........K......",
        ".K......K.......",
        "..K....K........",
        "...K..K..KK.....",
        "....KK....KK....",
        "................",
        "................",
    ],
    # Tabouret: coussin rond, colonne, repose-pieds, socle.
    "bar_stool": [
        "................",
        ".....CCCCCC.....",
        "....C111111C....",
        "....12222221....",
        ".....133331.....",
        "......sSs.......",
        "......sSs.......",
        "...SSSSSSSSSS...",
        "......sSs.......",
        "......sSs.......",
        "......sSs.......",
        "....SSSSSSSS....",
        "...SKKKKKKKKS...",
        "....KKKKKKKK....",
        "...KK......KK...",
        "................",
    ],
    # Comptoir: plateau bois, façade teinte, repose-pied chromé.
    "bar_counter": [
        ".BBBBBBBBBBBBBB.",
        ".bbbbbbbbbbbbbb.",
        ".SSSSSSSSSSSSSS.",
        ".k111111111111k.",
        ".k122222222221k.",
        ".k133333333331k.",
        ".k144444444441k.",
        ".kKKKKKKKKKKKKk.",
        ".k............k.",
        ".k.SSSSSSSSSS.k.",
        ".k.ssssssssss.k.",
        ".k............k.",
        ".KKKKKKKKKKKKKK.",
        "................",
        "................",
        "................",
    ],
    # Gradin: nez jaune, platelage, coque de siège.
    "bleacher": [
        ".............122",
        "............1331",
        "............1441",
        "...........12221",
        "..........133331",
        ".........1444441",
        "........11111111",
        "....YYYY........",
        "...BBBBBB.......",
        "..bbbbbbb....kk.",
        ".kkkkkkkk....kK.",
        "KKKKKKKK.....KK.",
        "................",
        "................",
        "................",
        "................",
    ],
    # Allée: deux marches bois à nez jaune, main courante, pas de siège.
    "bleacher_aisle": [
        "..........CC....",
        ".........C..C...",
        "........C....C..",
        ".......C..YYYC..",
        "......C..BBBBC..",
        ".....C....YYC...",
        "....C....BBBC...",
        "...C..YYY..C....",
        "..C..BBBB.C.....",
        ".CC..YYY.C......",
        ".kk.BBBB.C......",
        "KK......CC......",
        ".K..........K...",
        "................",
        "................",
        "................",
    ],
    # Sous-structure: montants, traverses, croix de Saint-André.
    "bleacher_support": [
        ".SssssssssssssS.",
        ".Sk..........kS.",
        ".S.k........k.S.",
        ".S..k......k..S.",
        ".S...k....k...S.",
        ".S....k..k....S.",
        ".S.....ss.....S.",
        ".S....k..k....S.",
        ".S...k....k...S.",
        ".S..k......k..S.",
        ".S.k........k.S.",
        ".Sk..........kS.",
        ".SssssssssssssS.",
        ".KK..........KK.",
        "KKK........KKKK.",
        "................",
    ],
    # Barrière Vauban: cadre, barreaux, trois pieds plats.
    "crowd_barrier": [
        ".CSSSSSSSSSSSSC.",
        ".SksksksksksksS.",
        ".S.s.s.s.s.s.sS.",
        ".SksksksksksksS.",
        ".S.s.s.s.s.s.sS.",
        ".SksksksksksksS.",
        ".S.s.s.s.s.s.sS.",
        ".CSSSSSSSSSSSSC.",
        "................",
        "..KKK..KKK..KKK.",
        ".KKKK.KKKK.KKKK.",
        "..kk...kk...kk..",
        "................",
        "................",
        "................",
        "................",
    ],
    # Potelet chromé, boule, corde velours, socle lesté.
    "stanchion": [
        ".......CC.......",
        "......CssC......",
        "......CKKC......",
        ".......ss.......",
        ".......ss.......",
        ".......ss..1....",
        ".......ss.121...",
        ".......s.1221...",
        ".......s12221...",
        "......s122221...",
        ".....s1222221...",
        "....KKKKKKKKK...",
        "...KKKKKKKKKKK..",
        "..KKKKKKKKKKKK..",
        "................",
        "................",
    ],
    # Tourniquet tripode: colonne, flèche verte, trois bras.
    "turnstile": [
        "..CSSSSSSC......",
        ".CSssssssSC.....",
        ".CSGGGGGGSC.....",
        ".CSssssssSC.....",
        "..CSSSSSSC......",
        "...SkkkkkS......",
        "...S....Sssss...",
        "...S....Ss......",
        "...S...sS.s.....",
        "...S..s.S..s....",
        "...S.s..S...s...",
        "...SSSSSS.......",
        "..KKKKKKKK......",
        ".KK....KK.......",
        "................",
        "................",
    ],
    # Rail de file: deux poteaux à boule, trois lisses.
    "guide_rail": [
        "CC............CC",
        "Ss............sS",
        "SSSSSSSSSSSSSSSS",
        "ss............ss",
        "ss............ss",
        "SSSSSSSSSSSSSSSS",
        "ss............ss",
        "ss............ss",
        "SSSSSSSSSSSSSSSS",
        "ss............ss",
        "Ss............sS",
        "KK............KK",
        "Kk............kK",
        ".KK..........KK.",
        "................",
        "................",
    ],
    # Stand de tir: auvent rayé, festons, canards, cibles, comptoir.
    "shooting_gallery": [
        ".YCYCYCYCYCYCYC.",
        "CRRRRRRRRRRRRRRC",
        "CWWWWWWWWWWWWWWC",
        ".RWRWRWRWRWRWRW.",
        "..Y..Y..Y..Y..Y.",
        "KKKKKKKKKKKKKKKK",
        "YYk.YYk.YYk.YYk.",
        "RWR.RWR.RWR.RWR.",
        ".BBBBBBBBBBBBBB.",
        "RWRWRWRWRWRWRWRW",
        "WRWRWRWRWRWRWRWR",
        ".KKKKKKKKKKKKKK.",
        "................",
        "................",
        "................",
        "................",
    ],
    # Barre de pont: tube avec un collier de serrage.
    "rigging_bar": [
        "................",
        "................",
        "................",
        "......KKKK......",
        ".....K....K.....",
        ".CCCCCCCCCCCCCC.",
        ".CssssssssssssC.",
        ".CSSSSSSSSSSSSC.",
        ".CssssssssssssC.",
        ".CkkkkkkkkkkkkC.",
        ".....K....K.....",
        "......KKKK......",
        "................",
        "................",
        "................",
        "................",
    ],
    # Table de pique-nique vue de profil: plateau, bancs, pieds en A.
    "picnic_table": [
        ".BBBBBBBBBBBBBB.",
        ".BbbbbbbbbbbbbB.",
        "..b..........b..",
        "..b.b......b.b..",
        "..b..b....b..b..",
        ".BB..b....b..BB.",
        ".bb..bbbbbb..bb.",
        ".....b....b.....",
        "....b......b....",
        "...b........b...",
        "..b..........b..",
        ".BB..........BB.",
        ".bb..........bb.",
        "................",
        "................",
        "................",
    ],
    # Parasol de profil: toile, mât, manivelle, pied en croix. La toile se teint.
    "parasol": [
        "................",
        "......1111......",
        ".....122221.....",
        "....12222221....",
        "...1222222221...",
        "..112222222211..",
        "..2222....2222..",
        ".......ss.......",
        ".......ss.......",
        ".......ssk......",
        ".......ss.k.....",
        ".......ss.......",
        ".......ss.......",
        "......ssss......",
        ".....KKKKKK.....",
        "......kkkk......",
    ],
    # Table pliante: plateau blanc, pieds noirs en X. Pas de teinte.
    "folding_table": [
        "................",
        "................",
        "................",
        "................",
        ".WWWWWWWWWWWWWW.",
        ".WssssssssssssW.",
        ".K..K......K..K.",
        ".K.KK......KK.K.",
        ".KK.K......K.KK.",
        ".K..KK....KK..K.",
        ".K...K....K...K.",
        ".K...KK..KK...K.",
        ".KK...K..K...KK.",
        "..K...K..K...K..",
        "................",
        "................",
    ],
    # Canon à eau: ventilateur, fût teinté, skid, roues.
    "water_cannon": [
        "...........11SS.",
        "..........1222S.",
        ".........13333S.",
        "........1444431.",
        ".......12222221.",
        "......133333331.",
        "..KKKK.1444441..",
        ".KkkkkK..SSSS...",
        ".Kk..kK.........",
        ".KkkkkK.........",
        "..KKKK..........",
        ".SSSSSSSSSSSSS..",
        ".S.KKK....KKKS..",
        "..KKKK....KKK...",
        "...kk......kk...",
        "................",
    ],
    # Coffret: câble enroulé, deux grosses prises rouges, petites bleues.
    "power_distro": [
        ".....kKKKKk.....",
        "....kK....Kk....",
        "...kKKKKKKKKk...",
        "..KKKKKKKKKKKK..",
        ".KKRRRRKKLLLLKK.",
        ".KKRKKRKKL.L.LK.",
        ".KKRKKRKKLLLLKK.",
        ".KKRRRRKKKKKKKK.",
        ".KKLLLLKKLLLLKK.",
        ".KKL.L.KKL.L.LK.",
        ".KKLLLLKKLLLLKK.",
        ".KKKKKKKKKKKKKK.",
        "..KKKKKKKKKKKK..",
        "..K..K....K..K..",
        "................",
        "................",
    ],
    # Rack de distribution: flight case, bandeau, prises bleues et rouges, roulettes.
    "power_rack": [
        ".CSSSSSSSSSSSSC.",
        ".CkKKKKKKKKKKkC.",
        ".C111111111111C.",
        ".Ck.CC.KK.CC.kC.",
        ".CKKKKKKKKKKKKC.",
        ".CKLLLKKRRRRRKC.",
        ".CKL.LKKR.RRRKC.",
        ".CKLLLKKRRRRRKC.",
        ".CKKKKKKKKKKKKC.",
        ".CKKLLKKKRRRRKC.",
        ".CKKL.LKKR.RRKC.",
        ".CKKLLKKKRRRRKC.",
        ".CkKKKKKKKKKKkC.",
        ".CSSSSSSSSSSSSC.",
        "..LL......LL....",
        "..KK......KK....",
    ],
    # Passage de câble, vu de bout : couvercle jaune, ailes noires, deux bouches, ergots.
    "cable_ramp": [
        "................",
        "................",
        "................",
        "................",
        "...kYYYYYYYYk...",
        "..kkYYYYYYYYkk..",
        ".kkkYkkkkkkYkkk.",
        "kkkkYk....kYkkkk",
        "KKKKYk....kYKKKK",
        "KKKK......KKKKKK",
        "KKKKKKKKKKKKKKKK",
        "K..KK......KK..K",
        "................",
        "................",
        "................",
        "................",
    ],
    # Rideau attaché : tringle, feston, deux pans et glands dorés. Le tissu se teint.
    "curtain": [
        "................",
        ".CSSSSSSSSSSSSC.",
        "1122112211221122",
        "2211221122112211",
        "22.11221122.1122",
        "2.............2.",
        "2Y...........Y2.",
        "2YY.........YY2.",
        "2.Y.........Y.2.",
        "2.Y.........Y.2.",
        "2.Y.........Y.2.",
        "22...........22.",
        "2.............2.",
        "2.............2.",
        "................",
        "................",
    ],
}


def write_all(assets):
    folder = os.path.join(assets, "textures", "item")
    os.makedirs(folder, exist_ok=True)
    for name, rows in ICONS.items():
        assert len(rows) == N and all(len(r) == N for r in rows), name
        base = Image.new("RGBA", (N, N), (0, 0, 0, 0))
        dyed = Image.new("RGBA", (N, N), (0, 0, 0, 0))
        for y, row in enumerate(rows):
            for x, ch in enumerate(row):
                if ch in FIXED:
                    base.putpixel((x, y), (*FIXED[ch], 255))
                elif ch in TINT:
                    v = TINT[ch]
                    dyed.putpixel((x, y), (v, v, v, 255))
        base.save(os.path.join(folder, name + ".png"))
        layers = {"layer0": f"stagetents:item/{name}"}
        if dyed.getbbox():
            dyed.save(os.path.join(folder, name + "_dye.png"))
            layers["layer1"] = f"stagetents:item/{name}_dye"
        with open(os.path.join(assets, "models", "item", name + ".json"), "w", encoding="utf-8", newline="\n") as f:
            json.dump({"parent": "item/generated", "textures": layers}, f, indent=2)
            f.write("\n")
    return sorted(ICONS)
