package com.nailec.stagetents.client;

import com.nailec.stagetents.StageTents;
import com.nailec.stagetents.tent.MobileStageShape;
import net.minecraft.client.Minecraft;
import net.minecraft.resources.ResourceLocation;

import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.IOException;
import java.io.InputStream;

/** Textured trailer geometry generated by tools/props/mobile_stage.py, baked into GPU buffers per placement. */
final class MobileStageMeshes {
    private static final ResourceLocation MODEL = new ResourceLocation(StageTents.MOD_ID, "models/structure/opus_4200.mesh");
    static final String[] MATERIALS = {"galvanised", "metal", "chrome", "black", "rubber", "stage_canvas",
            "stage_drape", "stage_deck", "tread", "red", "orange", "stage_label"};
    static final ResourceLocation[] TEXTURES = java.util.Arrays.stream(MATERIALS)
            .map(name -> new ResourceLocation(StageTents.MOD_ID, "textures/block/props/" + name + ".png"))
            .toArray(ResourceLocation[]::new);

    private MobileStageMeshes() {}

    private static InputStream open() throws IOException {
        // The standalone mesh dumper has no Minecraft instance. In game, honour resource packs and reloads.
        Minecraft game = Minecraft.getInstance();
        if (game != null) return game.getResourceManager().open(MODEL);
        InputStream stream = MobileStageMeshes.class.getResourceAsStream("/assets/" + MODEL.getNamespace() + "/" + MODEL.getPath());
        if (stream == null) throw new IOException("Missing " + MODEL);
        return stream;
    }

    static void build(MeshBuilder mesh, MobileStageShape shape) {
        try (DataInputStream in = new DataInputStream(new BufferedInputStream(open()))) {
            if (in.readInt() != 0x53544732) throw new IOException("Invalid stage mesh header");
            int count = in.readInt();
            if (count < 1 || count > 60_000) throw new IOException("Invalid stage triangle count: " + count);
            double[][] quad = new double[4][8];
            for (int i = 0; i < count; i++) {
                int material = in.readUnsignedByte();
                if (material >= MATERIALS.length) throw new IOException("Invalid stage material: " + material);
                for (double[] vertex : quad) {
                    for (int k = 0; k < vertex.length; k++) {
                        float value = in.readFloat();
                        if (!Float.isFinite(value)) throw new IOException("Non-finite stage vertex");
                        vertex[k] = value;
                    }
                }
                int tint = switch (material) {
                    case 5 -> shape.params.colorA;
                    case 6 -> shape.params.lining == -1 ? 0x24262A : shape.params.lining;
                    default -> 0xFFFFFF;
                };
                mesh.quad(quad, MeshBuilder.opaque(tint), MeshBuilder.MATERIAL + material, false);
            }
            if (in.read() != -1) throw new IOException("Unexpected data after stage mesh");
        } catch (IOException e) {
            throw new IllegalStateException("Unable to load the mobile stage geometry", e);
        }
    }
}
