package com.nailec.stagetents.client;

import com.nailec.stagetents.StageTents;
import com.nailec.stagetents.tent.MobileStageShape;
import net.minecraft.client.Minecraft;
import net.minecraft.resources.ResourceLocation;

import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.IOException;
import java.io.InputStream;

/** Textured trailer geometry generated by tools/props/mobile_stage.py, baked into GPU buffers per placement. */
final class MobileStageMeshes {
    private static final ResourceLocation MODEL = new ResourceLocation(StageTents.MOD_ID, "models/structure/opus_4200.mesh");
    static final String[] MATERIALS = {"galvanised", "metal", "chrome", "black", "rubber", "stage_canvas",
            "stage_drape", "stage_deck", "tread", "red", "orange", "stage_label"};
    static final ResourceLocation[] TEXTURES = java.util.Arrays.stream(MATERIALS)
            .map(name -> new ResourceLocation(StageTents.MOD_ID, "textures/block/props/" + name + ".png"))
            .toArray(ResourceLocation[]::new);

    private MobileStageMeshes() {}

    private static InputStream open() throws IOException {
        // The standalone mesh dumper has no Minecraft instance. In game, honour resource packs and reloads.
        Minecraft game = Minecraft.getInstance();
        if (game != null) return game.getResourceManager().open(MODEL);
        InputStream stream = MobileStageMeshes.class.getResourceAsStream("/assets/" + MODEL.getNamespace() + "/" + MODEL.getPath());
        if (stream == null) throw new IOException("Missing " + MODEL);
        return stream;
    }

    /** Decoded once. Each quad is material, part, then 4×8 floats (the fourth corner repeats the third). */
    private static int[] materials;
    private static int[] parts;
    private static float[] verts;

    static void build(MeshBuilder mesh, MobileStageShape shape) {
        ensure();
        float fold = StageFold.current;
        double[][] quad = new double[4][8];
        int count = materials.length;
        for (int i = 0; i < count; i++) {
            int material = materials[i];
            int base = i * 32;
            for (int v = 0; v < 4; v++) {
                for (int k = 0; k < 8; k++) quad[v][k] = verts[base + v * 8 + k];
            }
            StageFold.apply(quad, parts[i], fold);
            int tint = switch (material) {
                case 5 -> shape.params.colorA;
                case 6 -> shape.params.lining == -1 ? 0x24262A : shape.params.lining;
                default -> 0xFFFFFF;
            };
            mesh.quad(quad, MeshBuilder.opaque(tint), MeshBuilder.MATERIAL + material, false);
        }
    }

    private static void ensure() {
        if (verts != null) return;
        try (DataInputStream in = new DataInputStream(new BufferedInputStream(open()))) {
            int header = in.readInt();
            boolean partsInFile = header == 0x53544733;
            if (!partsInFile && header != 0x53544732) throw new IOException("Invalid stage mesh header");
            int count = in.readInt();
            if (count < 1 || count > 60_000) throw new IOException("Invalid stage triangle count: " + count);
            int[] mat = new int[count];
            int[] part = new int[count];
            float[] data = new float[count * 32];
            for (int i = 0; i < count; i++) {
                mat[i] = in.readUnsignedByte();
                if (mat[i] >= MATERIALS.length) throw new IOException("Invalid stage material: " + mat[i]);
                part[i] = partsInFile ? in.readUnsignedByte() : StageFold.BODY;
                for (int k = 0; k < 32; k++) {
                    float value = in.readFloat();
                    if (!Float.isFinite(value)) throw new IOException("Non-finite stage vertex");
                    data[i * 32 + k] = value;
                }
            }
            if (in.read() != -1) throw new IOException("Unexpected data after stage mesh");
            materials = mat;
            parts = part;
            verts = data;
        } catch (IOException e) {
            throw new IllegalStateException("Unable to load the mobile stage geometry", e);
        }
    }
}
